# === DİL GÜNCELLEMESİ ===
name: CI Build (Folyamatos Integrációs Build)
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - uses: actions/checkout@v4

      # === DİL GÜNCELLEMESİ ===
      - name: Node.js telepítése
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # === DİL GÜNCELLEMESİ ===
      - name: Függőségek telepítése
        run: npm ci

      # === DİL GÜNCELLEMESİ ===
      - name: Tesztek futtatása (ha van)
        run: npm run test --if-present

      # === DİL GÜNCELLEMESİ ===
      - name: Build (Oldal építése)
        run: npm run build

      # === DİL GÜNCELLEMESİ ===
      - name: Build artefaktumok feltöltése
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.node-version }}
          path: |
            build
            dist
            out